version: '3.9' # optional since v1.27.0
services:
    go-consistent-hashing:
        build: ./go-consistent-hashing
        environment:
            - CENTRAL_SERVER_PORT=6000
        ports:
            - 6000:6000
        expose:
            - 6000
        networks:
            - local
    go-http-redis-0:
        build: ./go-http-redis
        environment:
            - SERVER_PORT=5000
            - GIN_MODE=release
            - SERVER_NAME=server:0
        ports:
            - 5000:5000
        links:
            - redis
            - go-consistent-hashing
        depends_on:
            - go-consistent-hashing
        networks:
            - local
    go-http-redis-1:
        build: ./go-http-redis
        environment:
            - SERVER_PORT=5001
            - GIN_MODE=release
            - SERVER_NAME=server:1
        ports:
            - 5001:5001
        links:
            - redis
            - go-consistent-hashing
        depends_on:
            - go-consistent-hashing
        networks:
            - local
    go-http-redis-2:
        build: ./go-http-redis
        environment:
            - SERVER_PORT=5002
            - GIN_MODE=release
            - SERVER_NAME=server:2
        ports:
            - 5002:5002
        links:
            - redis
            - go-consistent-hashing
        depends_on:
            - go-consistent-hashing
        networks:
            - local
    go-http-redis-3:
        build: ./go-http-redis
        environment:
            - SERVER_PORT=5003
            - GIN_MODE=release
            - SERVER_NAME=server:3
        ports:
            - 5003:5003
        links:
            - redis
            - go-consistent-hashing
        depends_on:
            - go-consistent-hashing
        networks:
            - local
    go-http-redis-4:
        build: ./go-http-redis
        environment:
            - SERVER_PORT=5004
            - GIN_MODE=release
            - SERVER_NAME=server:4
        ports:
            - 5004:5004
        links:
            - redis
            - go-consistent-hashing
        depends_on:
            - go-consistent-hashing
        networks:
            - local
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        expose:
            - 6379
networks:
  local:
    driver: bridge
