###
GET http://localhost:3000/profile

###
GET http://localhost:3000/profile/key

###
POST http://localhost:3000/profile
Content-Type: application/json

{
    "id": "key",
    "value": true
}

# ###
# PUT http://localhost:3000/profile/key2
# Content-Type: application/json

# {
#     "value": false
# }

# PUT http://localhost:5000/key-value-pair
# Content-Type: application/json

# {
#     "node": "server:1",
#     "key": "aobo",
#     "value": "The queen"
# }

# ###
# DELETE http://localhost:5000/key-value-pair?node=server:1&key=aobo1

# ###
# POST http://localhost:5000/node
# Content-Type: application/json

# {
#     "node": "server:1",
#     "firstKey": "name",
#     "firstValue": "aobo"
# }

# ###
# DELETE http://localhost:5000/node?node=server:1

# ###
# GET http://localhost:5000/node-health

# ###
# POST http://localhost:5000/node-status
# Content-Type: application/json

# {
#     "status": "TERMINATING"
# }
